name: QuantumSim CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make check
        run: make check
      - name: make
        run: make

  build-macos-no-openmp:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: make check
        run: make check
      - name: make
        run: make

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: install libomp
        run: brew install libomp
      - name: Set environment variables for libomp
        run: |
          export LDFLAGS="-L$(brew --prefix libomp)/lib"
          export CPPFLAGS="-I$(brew --prefix libomp)/include"
      - name: make check
        run: make check
      - name: make
        run: make
