name: QuantumSim CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v2
      - name: Install OpenMP
        run: |
          sudo apt-get update
          sudo apt-get install -y libomp-dev
      - name: make check
        run: make check
      - name: make
        run: make

  build-macos:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, macos-15, macos-14, macos-13, macos-12, macos-11]

    steps:
      - uses: actions/checkout@v2
      - name: install libomp
        run: brew install libomp
      - name: Set environment variables for libomp
        run: |
          export LDFLAGS="-L$(brew --prefix libomp)/lib"
          export CPPFLAGS="-I$(brew --prefix libomp)/include"
      - name: make check
        run: make check
      - name: make
        run: make
